server:
  port: 8082

spring:
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka